<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "iu_viewhelpers"
 *
 * Auto generated by Extension Builder 2016-06-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Iunctim ViewHelpers',
	'description' => 'An extension as a library of Fluid Templates by iunctim',
	'category' => 'plugin',
	'author' => 'Tamim Wahage, Henning Lange, Jan C. Kranefeld',
	'author_email' => 'wahage@iunctim.com, lange@iunctim.com, kranefeld@iunctim.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '8.7.0-9.5.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
